apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdockerappsample-deployment
  # namespace: jaydeep
  labels:
    app: dotnetdockerappsample
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: dotnetdockerappsample
  template:
    metadata:
      labels:
        app: dotnetdockerappsample
    spec:
      containers:
      - name: dotnetdockerappsample
        image: 0000000000.dkr.ecr.fsa.amazonaws.com/dotnetappsampleecr:xyz
        ports:
        - containerPort: 5000
        startupProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5             
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"