apiVersion: v1
kind: Service
metadata:
  name: dotnetdockerappsample-service
  # namespace: jaydeep
spec:
  type: LoadBalancer
  # type: NodePort
  selector:
    app: dotnetdockerappsample
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000